server:
  port: 8021

spring:
  application:
    name: fdfs-service

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: zookeeper://192.168.0.111:2181
  scan:
    base-packages: io.example.service

fdfs:
  so-timeout: 1500
  connect-timeout: 1000
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.0.111:22122